#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
make_emoji.py — slices the 3 generated 3×3 emoji sheets into individual
transparent iPhone-style emoji images (public/assets/emoji/<key>.webp).
Each cell: flood-cut black bg → autocrop → square pad → 144px webp.
Also emits lib/emoji-assets.js (char → url map) for the app + canvas card.
Run: python3 scripts/make_emoji.py
"""
import os
from PIL import Image, ImageFilter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "raw-assets-new")
OUT = os.path.join(ROOT, "public", "assets", "emoji")
LIB = os.path.join(ROOT, "lib")
os.makedirs(OUT, exist_ok=True)

DARK = 58
SIZE = 144

# sheet file → 9 keys in row-major order (left→right, top→bottom)
SHEETS = {
    "emoji-sheet-1.png": ["heart", "teary", "laugh", "eyes", "flushed", "neutral", "pleading", "relieved", "smiling"],
    "emoji-sheet-2.png": ["coffee", "pan", "pizza", "clapper", "gift", "photo", "letter", "city", "party"],
    "emoji-sheet-3.png": ["moon", "sparkle", "tulip", "rose", "whiteheart", "seedling", "basket", "icecream", "mic"],
}

# char sequence (as in JS strings) → key  (longest first handled in JS)
CHARS = {
    "❤️": "heart", "❤": "heart",
    "🥹": "teary", "😂": "laugh", "👀": "eyes", "😳": "flushed", "😐": "neutral",
    "🥺": "pleading", "😌": "relieved", "☺️": "smiling", "☺": "smiling",
    "☕": "coffee", "🍳": "pan", "🍕": "pizza", "🎬": "clapper", "🎁": "gift",
    "📸": "photo", "💌": "letter", "🌃": "city", "🎉": "party",
    "🌙": "moon", "✨": "sparkle", "🌷": "tulip", "🌹": "rose", "🤍": "whiteheart",
    "🌱": "seedling", "🧺": "basket", "🍦": "icecream", "🎤": "mic",
}


def flood_cut(im):
    """حذف پس‌زمینه با flood-fill از لبه‌ها؛ خودکار تشخیص می‌دهد سیاه است یا سفید."""
    im = im.convert("RGB")
    w, h = im.size
    alpha = Image.new("L", (w, h), 255)
    px = im.load()
    visited = bytearray(w * h)
    stack = []
    corners = [px[2, 2], px[w - 3, 2], px[2, h - 3], px[w - 3, h - 3]]
    white_bg = all(r > 200 and g > 200 and b > 200 for (r, g, b) in corners)

    def push(x, y):
        i = y * w + x
        if visited[i]:
            return
        r, g, b = px[x, y]
        hit = (r > 205 and g > 205 and b > 205) if white_bg else (r < DARK and g < DARK and b < DARK)
        if hit:
            visited[i] = 1
            stack.append((x, y))

    for x in range(w):
        push(x, 0); push(x, h - 1)
    for y in range(h):
        push(0, y); push(w - 1, y)
    while stack:
        x, y = stack.pop()
        alpha.putpixel((x, y), 0)
        if x > 0: push(x - 1, y)
        if x < w - 1: push(x + 1, y)
        if y > 0: push(x, y - 1)
        if y < h - 1: push(x, y + 1)
    out = im.convert("RGBA")
    out.putalpha(alpha.filter(ImageFilter.GaussianBlur(0.6)))
    return out


def square_pad(im, ratio=1.06):
    bb = im.getchannel("A").getbbox()
    if not bb:
        return None
    im = im.crop(bb)
    s = int(max(im.size) * ratio)
    sq = Image.new("RGBA", (s, s), (0, 0, 0, 0))
    sq.alpha_composite(im, ((s - im.width) // 2, (s - im.height) // 2))
    return sq.resize((SIZE, SIZE), Image.LANCZOS)


def main():
    total = 0
    made = {}
    for fname, keys in SHEETS.items():
        sheet = Image.open(os.path.join(SRC, fname))
        W, H = sheet.size
        cw, ch = W / 3.0, H / 3.0
        for i, key in enumerate(keys):
            r, c = divmod(i, 3)
            # shrink cell a bit to avoid bleeding from neighbours
            x0, y0 = int(c * cw + cw * 0.05), int(r * ch + ch * 0.05)
            x1, y1 = int((c + 1) * cw - cw * 0.05), int((r + 1) * ch - ch * 0.05)
            cell = flood_cut(sheet.crop((x0, y0, x1, y1)))
            sq = square_pad(cell)
            if sq is None:
                print(f"!! EMPTY CELL: {fname} #{i} ({key})")
                continue
            path = os.path.join(OUT, key + ".webp")
            sq.save(path, "WEBP", quality=82, method=4)
            kb = os.path.getsize(path) / 1024
            total += kb
            made[key] = True
            print(f"{key:10s} → {kb:5.1f} KB")

    # emit JS map
    lines = ["// AUTO-GENERATED by scripts/make_emoji.py — emoji char → bundled image",
             "export const EMOJI_URL = {"]
    for ch, key in sorted(CHARS.items(), key=lambda kv: -len(kv[0])):
        if key in made:
            lines.append(f'  {ch!r}: "/assets/emoji/{key}.webp",')
    lines.append("};")
    lines.append("// longest-first char list for splitting text runs")
    lines.append("export const EMOJI_CHARS = Object.keys(EMOJI_URL).sort((a, b) => b.length - a.length);")
    with open(os.path.join(LIB, "emoji-assets.js"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"\ntotal: {total:.0f} KB · {len(made)} emoji")


if __name__ == "__main__":
    main()
